
package com.belajar.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserProfileService", targetNamespace = "http://service.belajar.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserProfileService {


    /**
     * 
     * @return
     *     returns com.belajar.service.UserProfile
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.belajar.com/UserProfileService/getUserProfileRequest", output = "http://service.belajar.com/UserProfileService/getUserProfileResponse")
    public UserProfile getUserProfile();

    /**
     * 
     * @param id
     * @return
     *     returns com.belajar.service.UserProfile
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.belajar.com/UserProfileService/getUserProfileByIdRequest", output = "http://service.belajar.com/UserProfileService/getUserProfileByIdResponse")
    public UserProfile getUserProfileById(
        @WebParam(name = "id", partName = "id")
        String id);

    /**
     * 
     * @param address
     * @param id
     * @param email
     * @param username
     * @return
     *     returns com.belajar.service.UserProfile
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.belajar.com/UserProfileService/setUserProfileRequest", output = "http://service.belajar.com/UserProfileService/setUserProfileResponse")
    public UserProfile setUserProfile(
        @WebParam(name = "id", partName = "id")
        String id,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "address", partName = "address")
        String address);

}
